# Generated by Django 3.2.8 on 2021-10-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('Kuchnia', 'kitchen'), ('Salon', 'living room'), ('Pokój', 'room'), ('Garaż', 'garage'), ('Przedpokój', 'hall'), ('Jadalnia', 'dining room'), ('Garderoba', 'walk-in wardrobe'), ('Spiżarnia', 'pantry'), ('Główna sypialnia', 'master bedroom'), ('Klatka schodowa', 'staircase'), ('Piwnica', 'basement'), ('Łazienka', 'bathroom')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='smart',
            name='smart',
            field=models.ManyToManyField(blank=True, null=True, to='strona.Service'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='furrowing',
            field=models.CharField(choices=[('płyta karton-gips', 'plasterboard'), ('beton', 'concrete'), ('pustak', 'airbrick'), ('cegła', 'brick'), ('drewno', 'wood')], max_length=20),
        ),
        migrations.AlterField(
            model_name='typeofspot',
            name='wall_type',
            field=models.CharField(choices=[('płyta karton-gips', 'plasterboard'), ('beton', 'concrete'), ('pustak', 'airbrick'), ('cegła', 'brick'), ('drewno', 'wood')], max_length=20),
        ),
    ]
